name: Update Submodule Ref in Parent Repo

on:
  push:
    branches:
      - main


jobs:
  update-submodule:
    runs-on: ubuntu-latest

    env:
      PARENT_REPO: kulupu-lapo/open
      PARENT_BRANCH: main
      SUBMODULE_PATH: poki

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone parent repository with submodules
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --recurse-submodules git@github.com:${{ env.PARENT_REPO }} parent-repo

      - name: Update submodule reference
        run: |
          cd parent-repo
          git submodule update --remote $SUBMODULE_PATH
          git add $SUBMODULE_PATH
          if git diff --cached --quiet; then
            echo "No changes detected in poki (parent repo already up to date). Exiting."
            exit 0
          fi
          if [ %(git log -1 --pretty=%B | sed -n '3p') -eq "!!!This is an automated commit by the poki bumper workflow!!!" ]; then
              git reset --soft HEAD~1
              $s=" (squashed commits)"
          fi
          git commit -m "Bump the poki version.$s
          
          !!!This is an automated commit by the poki bumper workflow!!!
          
          If the header line ends with "(squashed commits)", this commit contains 
          multiple bumps squashed together to prevent the history getting clogged
          up with them.
          "
          echo "Parent repo updated$s. Exiting."
